spring.application.name=pr-passos-spring-conf-properties
remetente.nome=Joao de Barro [via properties configuration remetente]
remetente.email=barro.joao@teste.com [via properties configuration remetente]
remetente.telefones=8488343232,8188297129 [via properties configuration remetente]
remetente.endereco=rua sem nome [via properties configuration remetente]
